apiVersion: v1
kind: ServiceAccount
metadata:
  name: knativeapp-pipeline-sa
  namespace: knativeapps
secrets:
  - name: knative-gcr-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: knativeapp-pipeline-sa
type: kubernetes.io/service-account-token

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knativeapp-pipeline-role
  namespace: knativeapps
rules:
- apiGroups: ["serving.knative.dev"]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knativeapp-pipeline-rb
  namespace: knativeapps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knativeapp-pipeline-role
subjects:
- kind: ServiceAccount
  name: knativeapp-pipeline-sa
