apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deploy-pipeline-sa
  namespace: github-deployment
secrets:
  - name: gcr-secret-push

---
apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: githubapp-pipeline-sa
type: kubernetes.io/service-account-token

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-deploy-pipeline-role
  namespace: github-deployment
rules:
- apiGroups: ["serving.knative.dev"]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deploy-pipeline-role-binding
  namespace: github-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-deploy-pipeline-role
subjects:
- kind: ServiceAccount
  name: github-deploy-pipeline-sa
