apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
   name: github-interceptor
   namespace: github-deployment
spec:
   serviceType: LoadBalancer
   serviceAccountName: tekton-triggers-connector-sa
   triggers:
    - name: github-deploy-trigger
      bindings:
        - ref: github-deploy-trigger-binding
      template:
        ref: github-deploy-trigger-template