# Values are provided from binding defined in triggerbinding else default value is used.
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-deploy-trigger-template
  namespace: github-deployment
spec:
  params:
  - name: revision
    description: Branch of Repository
    default: master
  - name: repoUrl
    description: Repository URL
    default: https://github.com/norepositotyfound.git
  resourceTemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: github-deploy-pipeline-run-
    spec:
      pipelineRef:
        name: github-deploy-pipeline
      serviceAccountName: github-deploy-pipeline-sa
      resources:
        - name: git-source
          resourceSpec:
            type: git
            params:
              - name: revision
                value: $(tt.params.revision)
              - name: url
                value: $(tt.params.repoUrl)