apiVersion: v1
data:
  .dockerconfigjson: "<cat ~/.docker/config.json | base64 -w 0>"
kind: Secret
metadata:
  name: gcr-secret-pull-image
  namespace: github-app-faas
type: kubernetes.io/dockerconfigjson