apiVersion: v1
data:
  .dockerconfigjson: BASE64STRING_OF_SECRETS
kind: Secret
metadata:
  creationTimestamp: null
  name: gcr-secret
  namespace: github-knative-apps
type: kubernetes.io/dockerconfigjson
