apiVersion: v1
data:
  .dockerconfigjson: $(cat ./secret.json|base64 -w 0)
kind: Secret
metadata:
  creationTimestamp: null
  name: gcr-secret-push
  namespace: github-deployment
type: kubernetes.io/dockerconfigjson