apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-deploy-trigger-binding
  namespace: github-deployment
spec:
  params:
    - name: revision
      value: master
    - name: repoUrl
      value: $(body.repoUrl)