apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-deploy-pipeline
  namespace: github-deployment
spec:
  resources:
    - name: git-source
      type: git
  params:
  - name: buildContext
    description: Path that will be used by kaniko for building
    default: './'
  - name: pathToYamlFile
    default: dir://$(git-source.path)/service.yaml
  - name: imageUrl
    default: asia.gcr.io/knativelocal/nodeapp
  - name: imageTag
    default: latest
  tasks:
  - name: build-source
    taskRef:
      name: source-to-image
    params:
    - name: buildContext
      value: "$(params.buildContext)"
    - name: pathToDockerfile
      value: "$(resources.inputs.git-source.path)/Dockerfile"
    resources:
      inputs:
        - name: git-source
          resource: git-source