apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: tekton-connectordeploy-binding
    namespace: github-deployment
subjects:
- kind: ServiceAccount
  name: tekton-triggers-connector-sa
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: tekton-trigger-connectordeploy-role