# Role required for triggerbinding and eventlistener to mutate configmap
# Permission for every EventListener deployment to function
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-trigger-github-deploy-role
  namespace: github-deployment
rules:
- apiGroups:
    - triggers.tekton.dev
  resources:
    - eventlisteners
    - triggerbindings
    - triggertemplates
    - pipelineresources
    - triggers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - configmaps
    - secrets
    - serviceaccounts
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - tekton.dev
  resources:
    - pipelineruns
    - pipelineresources
    - taskruns
  verbs:
    - create
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch
    - create
    - patch

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-trigger-github-deploy-role
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clustertriggerbindings"]
    verbs: ["get", "list", "watch"]