apiVersion: v1
kind: ConfigMap
metadata:
  name: payload-config
data:
  numOfRequest: "100"
  concurrency: "10"
  payload: '{"Payload":"{\"type\":\"action\",\"version\":\"v1\",\"func\":\"print\",\"input\":{\"log\":\"Hello I am Logger\"}}"}'
  host: github-nodeapp.github-app-faas.svc.cluster.local
  url: "http://github-nodeapp.github-app-faas.svc.cluster.local"